// GENERATED by read-as-book-pages — do not edit by hand.
// Re-run the command after changing report.pdf.

export const afterTheCorridorBook = {
  "generatedFrom": "report.pdf",
  "pageCount": 22,
  "aspect": 0.7727,
  "pages": [
    "publications/after-the-corridor/pages/p01.webp",
    "publications/after-the-corridor/pages/p02.webp",
    "publications/after-the-corridor/pages/p03.webp",
    "publications/after-the-corridor/pages/p04.webp",
    "publications/after-the-corridor/pages/p05.webp",
    "publications/after-the-corridor/pages/p06.webp",
    "publications/after-the-corridor/pages/p07.webp",
    "publications/after-the-corridor/pages/p08.webp",
    "publications/after-the-corridor/pages/p09.webp",
    "publications/after-the-corridor/pages/p10.webp",
    "publications/after-the-corridor/pages/p11.webp",
    "publications/after-the-corridor/pages/p12.webp",
    "publications/after-the-corridor/pages/p13.webp",
    "publications/after-the-corridor/pages/p14.webp",
    "publications/after-the-corridor/pages/p15.webp",
    "publications/after-the-corridor/pages/p16.webp",
    "publications/after-the-corridor/pages/p17.webp",
    "publications/after-the-corridor/pages/p18.webp",
    "publications/after-the-corridor/pages/p19.webp",
    "publications/after-the-corridor/pages/p20.webp",
    "publications/after-the-corridor/pages/p21.webp",
    "publications/after-the-corridor/pages/p22.webp"
  ]
} as const;
