// GENERATED by read-as-book-pages — do not edit by hand.
// Re-run the command after changing report.pdf.

export const agenticBehaviorObservatoryBook = {
  "generatedFrom": "report.pdf",
  "pageCount": 12,
  "aspect": 0.7067,
  "pages": [
    "publications/agentic-behavior-observatory/pages/p01.webp",
    "publications/agentic-behavior-observatory/pages/p02.webp",
    "publications/agentic-behavior-observatory/pages/p03.webp",
    "publications/agentic-behavior-observatory/pages/p04.webp",
    "publications/agentic-behavior-observatory/pages/p05.webp",
    "publications/agentic-behavior-observatory/pages/p06.webp",
    "publications/agentic-behavior-observatory/pages/p07.webp",
    "publications/agentic-behavior-observatory/pages/p08.webp",
    "publications/agentic-behavior-observatory/pages/p09.webp",
    "publications/agentic-behavior-observatory/pages/p10.webp",
    "publications/agentic-behavior-observatory/pages/p11.webp",
    "publications/agentic-behavior-observatory/pages/p12.webp"
  ]
} as const;
