// GENERATED by scripts/render-report-books.mjs — do not edit by hand.
//
// Registry of reports that have an old-school "book" view (a page-curl over the
// report's PDF, see ReportBook.tsx). Keyed by the report's slug so the report
// page and the /publications catalogue offer the book consistently.
//
// A report appears here once its pages have been rendered. Reports with a
// designed PDF use it directly; the rest are printed from their own printable
// edition at /print/<slug>.

import { afterTheCorridorBook } from "./after-the-corridor-book";
import { whatIsEthicalAiBook } from "./what-is-ethical-ai-book";

export type BookView = {
  pages: string[];
  aspect: number;
  /** The PDF these pages came from, under public/. */
  pdf: string;
};

export const bookViews: Record<string, BookView> = {
  "after-the-corridor": {
    pages: [...afterTheCorridorBook.pages],
    aspect: afterTheCorridorBook.aspect,
    pdf: "/publications/after-the-corridor/report.pdf",
  },
  "what-is-ethical-ai": {
    pages: [...whatIsEthicalAiBook.pages],
    aspect: whatIsEthicalAiBook.aspect,
    pdf: "/publications/what-is-ethical-ai/report.pdf",
  },
};

/** Find a book view from a publication URL like "/publications/after-the-corridor". */
export function bookForUrl(url?: string): BookView | undefined {
  if (!url) return undefined;
  const match = url.match(/\/publications\/([^/?#]+)/);
  return match ? bookViews[match[1]] : undefined;
}
