// GENERATED by scripts/render-report-books.mjs — do not edit by hand.
//
// Registry of reports that have an old-school "book" view (a page-curl over the
// report's PDF, see ReportBook.tsx). Keyed by the report's slug so the report
// page and the /publications catalogue offer the book consistently.
//
// A report appears here once its pages have been rendered. Reports with a
// designed PDF use it directly; the rest are printed from their own printable
// edition at /print/<slug>.

import { afterTheCorridorBook } from "./after-the-corridor-book";
import { agenticBehaviorObservatoryBook } from "./agentic-behavior-observatory-book";
import { agenticLanguageDevelopmentBook } from "./agentic-language-development-book";
import { aiCarbonFootprintBook } from "./ai-carbon-footprint-book";
import { aiModelsResearchBook } from "./ai-models-research-book";
import { aiResearchAssistantBook } from "./ai-research-assistant-book";
import { ceraiBook } from "./cerai-book";
import { cyberDictionaryBook } from "./cyber-dictionary-book";
import { digitalProvenancePassportBook } from "./digital-provenance-passport-book";
import { diplomaticSimulatorBook } from "./diplomatic-simulator-book";
import { ercfBook } from "./ercf-book";
import { erusBook } from "./erus-book";
import { evacuationInformIndexBook } from "./evacuation-inform-index-book";
import { evacuationSimulationBook } from "./evacuation-simulation-book";
import { forcedLaborStructuralRiskIndexBook } from "./forced-labor-structural-risk-index-book";
import { hasteBook } from "./haste-book";
import { mariupolSeverityModelBook } from "./mariupol-severity-model-book";
import { provenanceSearchBook } from "./provenance-search-book";
import { vangoBook } from "./vango-book";
import { warGamesBook } from "./war-games-book";
import { whatIsEthicalAiBook } from "./what-is-ethical-ai-book";

export type BookView = {
  pages: string[];
  aspect: number;
  /** The PDF these pages came from, under public/. */
  pdf: string;
};

export const bookViews: Record<string, BookView> = {
  "after-the-corridor": {
    pages: [...afterTheCorridorBook.pages],
    aspect: afterTheCorridorBook.aspect,
    pdf: "/publications/after-the-corridor/report.pdf",
  },
  "agentic-behavior-observatory": {
    pages: [...agenticBehaviorObservatoryBook.pages],
    aspect: agenticBehaviorObservatoryBook.aspect,
    pdf: "/publications/agentic-behavior-observatory/report.pdf",
  },
  "agentic-language-development": {
    pages: [...agenticLanguageDevelopmentBook.pages],
    aspect: agenticLanguageDevelopmentBook.aspect,
    pdf: "/publications/agentic-language-development/report.pdf",
  },
  "ai-carbon-footprint": {
    pages: [...aiCarbonFootprintBook.pages],
    aspect: aiCarbonFootprintBook.aspect,
    pdf: "/publications/ai-carbon-footprint/report.pdf",
  },
  "ai-models-research": {
    pages: [...aiModelsResearchBook.pages],
    aspect: aiModelsResearchBook.aspect,
    pdf: "/publications/ai-models-research/report.pdf",
  },
  "ai-research-assistant": {
    pages: [...aiResearchAssistantBook.pages],
    aspect: aiResearchAssistantBook.aspect,
    pdf: "/publications/ai-research-assistant/report.pdf",
  },
  cerai: {
    pages: [...ceraiBook.pages],
    aspect: ceraiBook.aspect,
    pdf: "/publications/cerai/report.pdf",
  },
  "cyber-dictionary": {
    pages: [...cyberDictionaryBook.pages],
    aspect: cyberDictionaryBook.aspect,
    pdf: "/publications/cyber-dictionary/report.pdf",
  },
  "digital-provenance-passport": {
    pages: [...digitalProvenancePassportBook.pages],
    aspect: digitalProvenancePassportBook.aspect,
    pdf: "/publications/digital-provenance-passport/report.pdf",
  },
  "diplomatic-simulator": {
    pages: [...diplomaticSimulatorBook.pages],
    aspect: diplomaticSimulatorBook.aspect,
    pdf: "/publications/diplomatic-simulator/report.pdf",
  },
  ercf: {
    pages: [...ercfBook.pages],
    aspect: ercfBook.aspect,
    pdf: "/publications/ercf/report.pdf",
  },
  erus: {
    pages: [...erusBook.pages],
    aspect: erusBook.aspect,
    pdf: "/publications/erus/report.pdf",
  },
  "evacuation-inform-index": {
    pages: [...evacuationInformIndexBook.pages],
    aspect: evacuationInformIndexBook.aspect,
    pdf: "/publications/evacuation-inform-index/report.pdf",
  },
  "evacuation-simulation": {
    pages: [...evacuationSimulationBook.pages],
    aspect: evacuationSimulationBook.aspect,
    pdf: "/publications/evacuation-simulation/report.pdf",
  },
  "forced-labor-structural-risk-index": {
    pages: [...forcedLaborStructuralRiskIndexBook.pages],
    aspect: forcedLaborStructuralRiskIndexBook.aspect,
    pdf: "/publications/forced-labor-structural-risk-index/report.pdf",
  },
  haste: {
    pages: [...hasteBook.pages],
    aspect: hasteBook.aspect,
    pdf: "/publications/haste/report.pdf",
  },
  "mariupol-severity-model": {
    pages: [...mariupolSeverityModelBook.pages],
    aspect: mariupolSeverityModelBook.aspect,
    pdf: "/publications/mariupol-severity-model/report.pdf",
  },
  "provenance-search": {
    pages: [...provenanceSearchBook.pages],
    aspect: provenanceSearchBook.aspect,
    pdf: "/publications/provenance-search/report.pdf",
  },
  vango: {
    pages: [...vangoBook.pages],
    aspect: vangoBook.aspect,
    pdf: "/publications/vango/report.pdf",
  },
  "war-games": {
    pages: [...warGamesBook.pages],
    aspect: warGamesBook.aspect,
    pdf: "/publications/war-games/report.pdf",
  },
  "what-is-ethical-ai": {
    pages: [...whatIsEthicalAiBook.pages],
    aspect: whatIsEthicalAiBook.aspect,
    pdf: "/publications/what-is-ethical-ai/report.pdf",
  },
};

/** Find a book view from a publication URL like "/publications/after-the-corridor". */
export function bookForUrl(url?: string): BookView | undefined {
  if (!url) return undefined;
  const match = url.match(/\/publications\/([^/?#]+)/);
  return match ? bookViews[match[1]] : undefined;
}
