// GENERATED by read-as-book-pages — do not edit by hand.
// Re-run the command after changing report.pdf.

export const digitalProvenancePassportBook = {
  "generatedFrom": "report.pdf",
  "pageCount": 28,
  "aspect": 0.7067,
  "pages": [
    "publications/digital-provenance-passport/pages/p01.webp",
    "publications/digital-provenance-passport/pages/p02.webp",
    "publications/digital-provenance-passport/pages/p03.webp",
    "publications/digital-provenance-passport/pages/p04.webp",
    "publications/digital-provenance-passport/pages/p05.webp",
    "publications/digital-provenance-passport/pages/p06.webp",
    "publications/digital-provenance-passport/pages/p07.webp",
    "publications/digital-provenance-passport/pages/p08.webp",
    "publications/digital-provenance-passport/pages/p09.webp",
    "publications/digital-provenance-passport/pages/p10.webp",
    "publications/digital-provenance-passport/pages/p11.webp",
    "publications/digital-provenance-passport/pages/p12.webp",
    "publications/digital-provenance-passport/pages/p13.webp",
    "publications/digital-provenance-passport/pages/p14.webp",
    "publications/digital-provenance-passport/pages/p15.webp",
    "publications/digital-provenance-passport/pages/p16.webp",
    "publications/digital-provenance-passport/pages/p17.webp",
    "publications/digital-provenance-passport/pages/p18.webp",
    "publications/digital-provenance-passport/pages/p19.webp",
    "publications/digital-provenance-passport/pages/p20.webp",
    "publications/digital-provenance-passport/pages/p21.webp",
    "publications/digital-provenance-passport/pages/p22.webp",
    "publications/digital-provenance-passport/pages/p23.webp",
    "publications/digital-provenance-passport/pages/p24.webp",
    "publications/digital-provenance-passport/pages/p25.webp",
    "publications/digital-provenance-passport/pages/p26.webp",
    "publications/digital-provenance-passport/pages/p27.webp",
    "publications/digital-provenance-passport/pages/p28.webp"
  ]
} as const;
