// GENERATED by read-as-book-pages — do not edit by hand.
// Re-run the command after changing report.pdf.

export const evacuationInformIndexBook = {
  "generatedFrom": "report.pdf",
  "pageCount": 15,
  "aspect": 0.7067,
  "pages": [
    "publications/evacuation-inform-index/pages/p01.webp",
    "publications/evacuation-inform-index/pages/p02.webp",
    "publications/evacuation-inform-index/pages/p03.webp",
    "publications/evacuation-inform-index/pages/p04.webp",
    "publications/evacuation-inform-index/pages/p05.webp",
    "publications/evacuation-inform-index/pages/p06.webp",
    "publications/evacuation-inform-index/pages/p07.webp",
    "publications/evacuation-inform-index/pages/p08.webp",
    "publications/evacuation-inform-index/pages/p09.webp",
    "publications/evacuation-inform-index/pages/p10.webp",
    "publications/evacuation-inform-index/pages/p11.webp",
    "publications/evacuation-inform-index/pages/p12.webp",
    "publications/evacuation-inform-index/pages/p13.webp",
    "publications/evacuation-inform-index/pages/p14.webp",
    "publications/evacuation-inform-index/pages/p15.webp"
  ]
} as const;
